automated/api/urls.py
# -*- encoding: utf-8 -*-
# @Time    : 18-10-17 上午9:21
# @Author  : mike.liu
# @File    : urls.py

from django.conf.urls import url

from api import api_views

app_name = 'api'
urlpatterns = [
    url(r'^$', api_views.index, name="index"),
    url(r'^apitest_manage/$', api_views.apitest_manage, name="apitest_manage"),
    url(r'^apistep_manage/$', api_views.apistep_manage, name="apistep_manage"),


]

automated/automated/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include


from api import urls
from test_platform import views
from api import api_views
from appui import app_views
from  webui import web_views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^register/$', views.register),
    url(r'^login/$', views.login),
    url(r'^index/$', views.login),
    url(r'^logout/$', views.logout),
    url(r'^home/$', views.home),

    # 项目
    url(r'^project/$', views.project),
    url(r'^add_project/$', views.add_project),
    url(r'^del_project/$', views.del_project),

    # 模块
    url(r'^modules/$', views.modules),
    url(r'^add_modules/$', views.add_modules),

    url(r'^toastr/$', views.toastr),

    # api子路由
    url(r'^api/', include('api.urls')),
    # appui子路由
    url(r'^appui/', include('appui.urls')),
    # webui子路由
    url(r'^webui/', include('webui.urls')),
]

automated/test_platform/forms.py
# -*- encoding: utf-8 -*-
# @Time    : 2018-09-29 23:20
# @Author  : mike.liu
# @File    : forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import widgets

from test_platform.models import UserInfo


class RegForm(forms.Form):
    username = forms.CharField(
        # 校验规则相关
        max_length=32,
        label="用户名",
        error_messages={
            "required": "该字段不能为空!",
        },
        # widget 控制的是生成HTML代码相关的
        widget=widgets.TextInput(attrs={"class": "form-control"},)
    )

    password = forms.CharField(
        min_length=6,
        max_length=16,
        label="密码",
        widget=widgets.PasswordInput(attrs={"class": "form-control"}, render_value=True),
        error_messages={
            "min_length": "密码不能少于6位!",
            "max_length": "密码长度不能大于16位!",
            "required": "该字段不能为空!",
        }
    )

    re_password = forms.CharField(
        min_length=6,
        max_length=16,
        label="确认密码",
        widget=widgets.PasswordInput(attrs={"class": "form-control"}, render_value=True),
        error_messages={
            "min_length": "密码不能少于6位!",
            "max_length": "密码长度不能大于16位!",
            "required": "该字段不能为空!",
        }
    )

    email = forms.EmailField(
        label="邮箱地址",
        max_length=64,
        widget=widgets.EmailInput(attrs={"class": "form-control"}),
        error_messages={
            "required": "该字段不能为空!",
            "invalid": "邮箱格式错误!",
        }
    )

    # 局部钩子
    def clean_username(self):
        value = self.cleaned_data.get("username")

        username = UserInfo.objects.filter(username=value).first()

        if not username:
            return value
        else:
            raise ValidationError("该用户已注册!")

    # 全局钩子
    def clean(self):
        password = self.cleaned_data.get("password")
        re_password = self.cleaned_data.get("re_password")

        if password and re_password:
            if password == re_password:
                return self.cleaned_data
            else:
                raise ValidationError("两次密码不一致!")

        else:
            return self.cleaned_data

automated/templates/apistep_manage.html
{% extends "home.html" %}

{% block add %}

<!--按钮-->
<div class="btn-toolbar" role="toolbar">
  <div class="btn-group" style="padding-top: 100px; left: 350px">
    <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#addmyModal">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> 添加
    </button>
    <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
        <span class="glyphicon glyphicon-edit" aria-hidden="true"></span> 修改
    </button>
  </div>

</div>

<!--项目列表-->
<div class="container">
        <div class="row" style="padding-top: 80px;">
            <div class="col-md-10 col-md-offset-3">

                <table class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>选中</th>
                            <th>所属用例</th>
                            <th>项目名称</th>
                            <th>模块名称</th>
                            <th>测试步骤</th>
                            <th>URL地址</th>
                            <th>请求方法</th>
                            <th>参数=值</th>
                            <th>预期结果</th>
                            <th>实际结果</th>
                            <th>执行时间</th>


                        </tr>
                    </thead>
                    <tbody>
                        {% for modules_obj in modules_list %}
                            <tr>
                                <td id="che1"><input type="checkbox"/></td>
                                <td>{{ modules_obj.mid }}</td>
                                <td>{{ modules_obj.modules_name }}</td>
                                <td>{{ modules_obj.modules_desc }}</td>
                                <td>{{ modules_obj.testers }}</td>
                                <td>{{ modules_obj.create_time|date:'Y-m-d' }}</td>


                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock %}

automated/templates/apitest_manage.html
{% extends "home.html" %}

{% block add %}

<!--按钮-->
<div class="btn-toolbar" role="toolbar">
  <div class="btn-group" style="padding-top: 100px; left: 350px">
    <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#addmyModal">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> 添加
    </button>
    <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
        <span class="glyphicon glyphicon-edit" aria-hidden="true"></span> 修改
    </button>
  </div>

</div>

<!--项目列表-->
<div class="container">
        <div class="row" style="padding-top: 80px;">
            <div class="col-md-10 col-md-offset-3">

                <table class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>选中</th>
                            <th>用例id</th>
                            <th>项目名称</th>
                            <th>模块名称</th>
                            <th>接口测试用例名称</th>
                            <th>接口描述</th>
                            <th>测试人员</th>
                            <th>测试结果</th>
                            <th>操作</th>


                        </tr>
                    </thead>
                    <tbody>
                        {% for modules_obj in modules_list %}
                            <tr>
                                <td id="che1"><input type="checkbox"/></td>
                                <td>{{ modules_obj.mid }}</td>
                                <td>{{ modules_obj.modules_name }}</td>
                                <td>{{ modules_obj.modules_desc }}</td>
                                <td>{{ modules_obj.testers }}</td>
                                <td>{{ modules_obj.create_time|date:'Y-m-d' }}</td>
                                <td>
                                    <a href="/books/{{ book.pk }}/change"><button class="btn btn-info">查看</button></a>
                                    <a href="/books/{{ book.pk }}/change"><button class="btn btn-info">编辑</button></a>
                                    <a href="/books/{{ book.pk }}/change"><button class="btn btn-info">删除</button></a>
                                </td>


                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

<!-- 新增接口测试用例模态框 -->
    <div class="modal fade" id="addmyModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">添加接口测试用例</h4>
          </div>
          <div class="modal-body">
              <form role="form">
                  {% csrf_token %}
                  <div class="form-group">
                    <label for="project_id">项目名称</label>
                    <select name="project_id" id="project_id" class="form-control">
                            {% for project_obj in project_list %}
                            <option value="{{project_obj.pk}}">{{project_obj.project_name}}</option>
                            {% endfor %}
                        </select>
                  </div>
                  <h6 style="color: red"><span class="error"></span></h6>

                  <div class="form-group">
                    <label for="module_id">模块名称</label>
                    <select name="module_id" id="module_id" class="form-control">
                            {% for module_id_obj in module_id_list %}
                            <option value="{{module_id.pk}}">{{module_id.module_name}}</option>
                            {% endfor %}
                        </select>
                  </div>
                  <div class="form-group">
                    <label for="api_case_name">接口测试用例名称</label>
                    <input type="text" name="api_case_name" id="api_case_name" class="form-control" placeholder="输入接口测试用例名称">
                  </div>
                  <div class="form-group">
                    <label for="api_desc">接口描述</label>
                    <input type="text" name="api_desc" id="api_desc" class="form-control" placeholder="输入项目描述">
                  </div>

                  <div class="form-group">
                    <label for="testers">测试人员</label>
                    <input type="text" name="testers" id="testers" class="form-control" placeholder="输入测试人员">
                  </div>

                  <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                    <button type="button" class="btn btn-primary add_api_case">提交</button>
                  </div>

              </form>

          </div>

        </div>
      </div>
    </div>
{% endblock %}

automated/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>自动化测试平台</title>
    <link rel="stylesheet" href="/static/bootstrap-3.3.7/css/bootstrap.css">
    <link rel="stylesheet" href="/static/css/toastr.min.css">
    <script src="/static/js/jquery-3.3.1.js"></script>
    <script src="/static/bootstrap-3.3.7/js/bootstrap.min.js"></script>
    <script src="/static/js/toastr.min.js"></script>
    <link rel="stylesheet" href="/static/css/dashboard.css">
    <link rel="stylesheet" href="/static/css/home.css">

    <style>
        #user_icon {
            font-size: 18px;
            margin-right: 10px;
            vertical-align: -3px;
        }

    </style>
</head>
<body>

<nav class="tab navbar  navbar-fixed-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">金斧子自动化测试平台</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

            <ul class="nav navbar-nav navbar-right">
                <li class="active"><a href="#">web自动化 <span class="sr-only">(current)</span></a></li>
                <li><a href="#">APP自动化</a></li>
                <li><a href="#">接口自动化</a></li>

                <li><a href="#"><span id="user_icon"
                                      class="glyphicon glyphicon-user"></span>{{ request.user.username }}</a></li>
                <li><a href="/logout/">注销</a></li>
                <li><a href="/set_pwd/">修改密码</a></li>


            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
<!--左侧菜单-->
<div class="container">
    <div class="left">
        <div class="row">
            <div class="col-sm-3 col-md-2 sidebar">
                <div class="menu">
                    <div class="head bg-primary">项目管理</div>
                    <ul class="nav nav-sidebar">
                        <li><a href="/project/" target="_self">测试项目</a> </li>
                        <li><a href="/modules/" target="_self">测试模块</a> </li>

                    </ul>
                </div>

                <div class="menu">
                    <div class="head bg-primary">APP自动化用例管理</div>
                    <ul class="nav nav-sidebar">
                        <li><a href="#">APP测试用例</a> </li>
                        <li><a href="#">APP测试步骤</a> </li>
                        <li><a href="#">APP测试结果</a> </li>
                    </ul>
                </div>
                <div class="menu">
                    <div class="head bg-primary">web自动化用例管理</div>
                    <ul class="nav nav-sidebar">
                        <li><a href="#">web测试用例</a> </li>
                        <li><a href="#">web测试步骤</a> </li>
                        <li><a href="#">web测试结果</a> </li>
                    </ul>
                </div>
                <div class="menu">
                    <div class="head bg-primary">接口自动化用例管理</div>
                    <ul class="nav nav-sidebar">
                        <li><a href="/api/apitest_manage/" target="_self">接口测试用例</a> </li>
                        <li><a href="/api/apistep_manage/" target="_self">接口步骤</a> </li>
                        <li><a href="#">单一接口</a> </li>
                        <li><a href="#">接口测试结果</a> </li>
                    </ul>
                </div>
                <div class="menu">
                    <div class="head bg-primary">测试任务</div>
                    <ul class="nav nav-sidebar">
                        <li><a href="#">添加定时任务</a> </li>
                        <li><a href="#">查看定时任务</a> </li>

                    </ul>
                </div>
            </div>
        </div>

    </div>

    <div class="right">

        {#表格#}
        {% block add %}
            <h1>欢迎csfsdfsdsdsdsdsdsdsdsdsdsdsdsdsdsdsdsdsdes</h1>
        {% endblock %}
    </div>
</div>


<script src="/static/js/jquery-3.3.1.js"></script>
<script src="/static/bootstrap-3.3.7/js/bootstrap.min.js"></script>
<script>
    // 左侧菜单
    $(".head").on("click",function(){
        //兄弟标签紧挨着的ul标签隐藏addclass("hide")
        $(this).parent().siblings().children("ul").slideUp();
        //把自己紧挨着的ul标签显示removeClass("hide")
            $(this).next().removeClass("hide");
        $(this).next().slideToggle();
    });
</script>

<script>

        toastr.options= {
                "closeButton":false,//显示关闭按钮
                "debug":false,//启用debug
                "positionClass":"toast-top-center",//弹出的位置
                "showDuration":"300",//显示的时间
                "hideDuration":"1000",//消失的时间
                "timeOut":"5000",//停留的时间
                "extendedTimeOut":"1000",//控制时间
                "showEasing":"swing",//显示时的动画缓冲方式
                "hideEasing":"linear",//消失时的动画缓冲方式
                "showMethod":"fadeIn",//显示时的动画方式
                "hideMethod":"fadeOut"//消失时的动画方式
                };
        // // 新建项目验证

    $(".btn_sub").click(function () {

        $.ajax({
            url: "/add_project/",
            type: "post",
            data: {
                project_name: $("#project_name").val(),
                project_desc: $("#project_desc").val(),
                testers: $("#testers").val(),
                csrfmiddlewaretoken: $("[name='csrfmiddlewaretoken']").val(),
            },
            success: function (data) {

                if (data.status== 0) {
                    // alert(111)
                    toastr.success('新增项目成功');
                    if (location.search){
                            location.href = location.search.slice(6)
                    }
                    else {
                        setTimeout(function () {
                            location.href = "/project/"
                        }, 2000)

                    }

                }
                else {


                    $(".error").text(data.msg);
                    setTimeout(function () {
                        $(".error").text("");

                    }, 5000)
                }



            }

        })
    });


 // 新建模块验证

    $(".add_module").click(function () {

        $.ajax({
            url: "/add_modules/",
            type: "post",
            data: {
                project_id: $("#project_id").val(),
                modules_name: $("#modules_name").val(),
                modules_desc: $("#modules_desc").val(),
                testers: $("#testers").val(),
                csrfmiddlewaretoken: $("[name='csrfmiddlewaretoken']").val(),
            },
            success: function (data) {

                if (data.status== 0) {
                    toastr.success('新增模块成功');

                    setTimeout(function () {
                        location.href = "/modules/"
                    }, 2000)


                }

                else {


                    $(".error").text(data.msg);
                    setTimeout(function () {
                        $(".error").text("");

                    }, 5000)
                }



            }

        })
    })


    // 删除

    $("#btn_del").click(function () {
        var env_ids = new Array();
        var count = 0;
        var i = 0;
        $("#myAlert1").css("display","none");
        $("#table").find(":checkbox:checkbox").each(function () {
            env_id = $(this).parent().next().text();
            alert(env_id)
            if(env_id != ""){
                env_ids[i++] = env_id;
            }
            count ++;

        });
        if (count==0){
            $("#myAlert1").css("display", "inherit");
            return false;
        }
        else {
            $("#ipt1").val(env_ids);
            $("#del").submit();
        }
    });

// 新建接口测试用例

    $(".add_api_case").click(function () {

        $.ajax({
            url: "/add_api_case/",
            type: "post",
            data: {
                project_id: $("#project_id").val(),
                module_id: $("#module_id").val(),
                api_case_name: $("#api_case_name").val(),
                api_desc: $("#api_desc").val(),
                testers: $("#testers").val(),
                csrfmiddlewaretoken: $("[name='csrfmiddlewaretoken']").val(),
            },
            success: function (data) {

                if (data.status== 0) {
                    toastr.success('新增接口测试用例成功');

                    setTimeout(function () {
                        location.href = "/apitest_manage/"
                    }, 2000)


                }

                else {


                    $(".error").text(data.msg);
                    setTimeout(function () {
                        $(".error").text("");

                    }, 5000)
                }



            }

        })
    })




</script>
</body>
</html>

automated/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>自动化测试平台</title>
    <link rel="stylesheet" href="/static/bootstrap-3.3.7/css/bootstrap.css">
    <script src="/static/jquery-3.3.1.js"></script>
    <script src="/static/bootstrap-3.3.7/js/bootstrap.min.js"></script>
    <style>
        #user_icon {
            font-size: 18px;
            margin-right: 10px;
            vertical-align: -3px;
        }

    </style>
</head>
<body>

<nav class="tab navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">金斧子自动化测试平台</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">web自动化 <span class="sr-only">(current)</span></a></li>
                <li><a href="#">APP自动化</a></li>
                <li><a href="#">接口自动化</a></li>

            </ul>

            <ul class="nav navbar-nav navbar-right">

                {% if request.user.is_authenticated %}
                    <li><a href="#"><span id="user_icon"
                                          class="glyphicon glyphicon-user"></span>{{ request.user.username }}</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">个人设置 <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">修改密码</a></li>
                            <li><a href="#">修改头像</a></li>

                            <li><a href="/logout/">注销</a></li>
                            <li role="separator" class="divider"></li>

                        </ul>
                    </li>

                {% else %}
                    <li><a href="/login/">登录</a></li>
                    <li><a href="/register/">注册</a></li>
                {% endif %}


            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

</body>
</html>

automated/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>自动化测试平台</title>
    <link rel="stylesheet" href="/static/bootstrap-3.3.7/css/bootstrap.css">
    <link rel="stylesheet" href="/static/css/toastr.min.css">
    <script src="/static/js/jquery-3.3.1.js"></script>
    <script src="/static/bootstrap-3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="/static/css/login_reg.css">
    <script src="/static/js/toastr.min.js"></script>

</head>
<body>
    <nav class="tab navbar  navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <h3>金斧子自动化测试平台</h3>
            </div>

        </div>
        
    </nav>
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    <form>
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="username">用户名</label>
                            <input type="text" id="username" class="form-control" placeholder="输入用户名">
                        </div>

                         <div class="form-group">
                            <label for="password">密码</label>
                            <input type="password" id="password" class="form-control" placeholder="输入密码">
                        </div>

                        <input type="button" class="btn btn-primary login_btn" value="登录"><span class="error"></span>
                        <a href="/register/"><input type="button" class="btn pull-right" value="注册"></a>
                    </form>
                </div>
            </div>
        </div>


        <script>
            // 登录验证
            $(".login_btn").click(function () {

                $.ajax({
                    url:"",
                    type: "post",
                    data:{
                        username: $("#username").val(),
                        password: $("#password").val(),
                        csrfmiddlewaretoken: $("[name='csrfmiddlewaretoken']").val(),
                    },
                    success: function (data) {
                        console.log(data);


                        if (data.username){

                            if (location.search){
                                location.href = location.search.slice(6)
                            }
                            else {

                                    location.href = "/home/"



                            }
                        }
                        else {
                            alert(222)
                            $(".error").text(data.msg);
                            setTimeout(function () {
                                $(".error").text("")

                            }, 5000)
                        }

                    }
                })

            })
        </script>

</body>
</html>

automated/templates/nav.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>自动化测试平台</title>
    <link rel="stylesheet" href="/static/bootstrap-3.3.7/css/bootstrap.css">
    <script src="/static/js/jquery-3.3.1.js"></script>
    <script src="/static/bootstrap-3.3.7/js/bootstrap.min.js"></script>

</head>
<body>

<nav class="tab navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">金斧子自动化测试平台</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <!--<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">-->


            <!--<ul class="nav navbar-nav navbar-right">-->

                    <!--<li><a href="/login/">登录</a></li>-->
                    <!--<li><a href="/register/">注册</a></li>-->


            <!--</ul>-->
        <!--</div>&lt;!&ndash; /.navbar-collapse &ndash;&gt;-->
    </div><!-- /.container-fluid -->
</nav>

</body>
</html>

automated/templates/reg_succes.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h3>恭喜{{username}},{{s}}!现在就去<a href="/login/"> 登录 </a></h3>


</body>
</html>

automated/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册页面</title>
    <link rel="stylesheet" href="../static/bootstrap-3.3.7/css/bootstrap.css">
    <link rel="stylesheet" href="/static/css/toastr.min.css">
    <script src="../static/js/jquery-3.3.1.js"></script>
    <link rel="stylesheet" href="/static/css/login_reg.css">
    <script src="/static/js/toastr.min.js"></script>

</head>
<body>
    <nav class="tab navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <h3>金斧子自动化测试平台</h3>
            </div>

        </div>
    </nav>

<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <form id="form">
                {% csrf_token %}
                {% for reg_obj in form %}
                    <div class="form-group">
                        <label for="{{ reg_obj.auto_id }}">{{ reg_obj.label }}</label>
                        {{ reg_obj }} <span class="error pull-right"></span>
                    </div>
                {% endfor %}

                <input type="button" class="btn btn-default reg_btn" value="注册"><span class="error"></span>
                <a href="/login/"><input type="button" class="btn pull-right" value="返回"></a>
            </form>
        </div>
    </div>
</div>

<script>
    toastr.options= {
                "closeButton":false,//显示关闭按钮
                "debug":false,//启用debug
                "positionClass":"toast-top-center",//弹出的位置
                "showDuration":"300",//显示的时间
                "hideDuration":"1000",//消失的时间
                "timeOut":"5000",//停留的时间
                "extendedTimeOut":"1000",//控制时间
                "showEasing":"swing",//显示时的动画缓冲方式
                "hideEasing":"linear",//消失时的动画缓冲方式
                "showMethod":"fadeIn",//显示时的动画方式
                "hideMethod":"fadeOut"//消失时的动画方式
                };

    // 基于Ajax提交数据
    $(".reg_btn").click(function () {

        var formdata = new FormData();
        var request_data = $("#form").serializeArray();
        $.each(request_data, function (index, data) {
            formdata.append(data.name ,data.value)

        });

        $.ajax({
            url:"",
            type: "post",
            contentType: false,
            processData: false,
            data: formdata,
            success: function (data) {


                if(data.username){
                    // 注册成功
                    toastr.success('注册成功');
                    setTimeout(function () {
                        location.href="/login/"
                    }, 1000)



                }
                else {
                    //注册失败
                    // 清空错误信息
                    toastr.error("注册失败");
                    $("span.error").html("");
                    $(".form-group").removeClass("has-error");

                    // 展示此次提交的错误信息
                    $.each(data.msg, function (reg_obj, error_list) {
                        if (reg_obj=="__all__"){
                            $("#id_re_password").next().html(error_list[0]).parent().addClass("has-error");

                        }
                        $("#id_" + reg_obj).next().html(error_list[0]);
                        $("#id_" + reg_obj).parent().addClass("has-error");
                        // 3秒之后清空错误提示信息
                        setTimeout(function () {
                            $(".error").text("");

                        }, 3000)

                    })

                }

            }
        })


    })
</script>
</body>
</html>